### ISSUE TITLE
Provide a way to use the --namespace from helm

### ISSUE THREAD

**Issue by enriched** [streamnative/charts#100]
Currently pulsar chart provides a way to specify the namespace using `.Values.namepsace`. I would propose that when the .Values.namespace is not defined, the chart falls back to using `.Release.Namespace`.

I think this would make the chart easier to reuse in other charts while still allowing the namespace to be set explicitly.

There is some discussion around best practices for helm namespaces [here](https://github.com/helm/helm/issues/5465)

**Comment by sijie** [comment]
@enriched that is a good idea. Are you interested in contributing a pull request?

**Comment by enriched** [comment]
Absolutely, will try to get one knocked out today.
