### ISSUE TITLE
Allow for allow for templating of configData values

### ISSUE THREAD

**Issue by enriched** [streamnative/charts#104]
When reusing the pulsar chart, some of the values can be dependent on values used elsewhere (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) or the name of the release (s3ManagedLedgerOffladServiceEndpoint).

I propose that we [use helm's tmpl function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) to allow references to other values from within values supplied to the chart.

**Comment by jiazhai** [comment]
Thanks @enriched for rising up this issue. It looks good. Would you like to provide a PR for this feature?

**Comment by enriched** [comment]
Sure! I will try to get a PR in this week.

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
