### ISSUE TITLE
Helm namespace support cont.

### ISSUE THREAD

**Issue by austince** [streamnative/charts#105]
We've found a few missed instances of the old way of setting the `namespace` in some of the `.tpl` files:

https://github.com/streamnative/charts/blob/58b0b8bba556fff959425b9fc229606dda77cf9d/charts/pulsar/templates/zookeeper/_zookeeper.tpl#L23-L25

I've found reference to the direct `.namespace` value in the following directories' `_{dir}.tpl`
- autorecovery
- bookkeeper
- broker
- pulsar_manager
- toolset
- zookeeper

_Originally posted by @austince in https://github.com/streamnative/charts/pull/101#issuecomment-646873651_

**Comment by austince** [comment]
@enriched, does this look good to you?

**Comment by enriched** [comment]
Yeah, looks great. I will try to hop on this today and get it fixed, unless you already have the changes needed?

**Comment by austince** [comment]
Unfortunately, I haven't had time yet -- if you don't get to it today I'll probably have time by the end of the week.

**Comment by wolfstudy** [comment]
https://github.com/streamnative/charts/pull/106
