### ISSUE TITLE
Bump chart version

### ISSUE THREAD

**Issue by jonaskint** [streamnative/charts#109]
I've ran against an issue that got resolved in [#108](https://github.com/streamnative/charts/pull/108) but the chart did not get bumped. Is there anything i can do to help this getting released?

It contains a fix for the offloading that i am looking to introduce in our stack.

Thanks in advance!

**Comment by jonaskint** [comment]
https://github.com/streamnative/charts/pull/110

**Comment by sijie** [comment]
@jonaskint you can submit a pull request to bump the version of `1.2.0` to `1.2.1` (https://github.com/streamnative/charts/blob/master/charts/pulsar/Chart.yaml#L24). Then we can review and merge it. Once it is merged, that chart will be published.
