### ISSUE TITLE
[charts/sn-platform] pulsar detector only support "token" auth in template.

### ISSUE THREAD

**Issue by yuweisung** [streamnative/charts#1093]
from the sn-plugin/pulsar-detector repo, detector supports token and tls authentication.
The template in /charts/sn-platform/templates/detector/pulsar-detector-deployment.yaml line 114 only support "token" (auth-plugin is hardcoded with token).
request: add an option to support tls.

**Comment by ericsyh** [comment]
fixed by https://github.com/streamnative/charts/pull/1124
