### ISSUE TITLE
pulsar-manager.configmap has invalid/empty redirect.host value

### ISSUE THREAD

**Issue by mkoertgen** [streamnative/charts#111]
With chart version 1.2.1 the pulsar-manager-configmap has no value for `redirect.host` resulting in pulsar-manager failing to start with illegal argument syntax.

Seems like a regression bug. In 1.2.0 it was ` --redirect.host=admin.pulsar.pulsar.example.local`

**Comment by sijie** [comment]
`redirect.host` is defined in the values.yaml. I have used the 1.2.1 chart. It seems to fine to me.

Do you have a sample values file? I would like to see if I can reproduce it.

**Comment by mkoertgen** [comment]
@sijie Thanks for reaching out. We installed without user-supplied values. Upgrading from 1.2.0 failed with a message that some field could not be patched.

We then just did 
- helm delete (1.2.0)
- also removed the pvc & left-over functions
- helm install (1.2.1)

Everything went quick & fine (seemed as if the docker images did not change too much) except the pulsar-manager could not start because of the reasons described above.

Just an idea into the blue: Would we have to remove some other left-overs, e.g. secrets or configmaps?

**Comment by Celebfie** [comment]
Facing the same issue, I am using the official doc of stream native  

<img width="885" alt="Screenshot 2020-07-13 at 4 35 36 PM" src="https://user-images.githubusercontent.com/53039640/87297936-e2a33f80-c526-11ea-8b84-b58c07807e0a.png">
<img width="1280" alt="Screenshot 2020-07-13 at 4 36 04 PM" src="https://user-images.githubusercontent.com/53039640/87297966-f2bb1f00-c526-11ea-85ba-3f187e427d86.png">

**Comment by Celebfie** [comment]
<img width="1127" alt="Screenshot 2020-07-13 at 4 40 24 PM" src="https://user-images.githubusercontent.com/53039640/87298279-8e4c8f80-c527-11ea-9699-d49da170202b.png">

**Comment by sijie** [comment]
@Celebfie @mkoertgen I have sent out a pull request for fixing it.
