### ISSUE TITLE
JWT authentication not working with Pulsar manager 

### ISSUE THREAD

**Issue by kapilsingh421** [streamnative/charts#113]
I enabled JWT Authentication in values.YAML then upgraded the chart and somehow Pulsar manager stops working.
Error In pulsar manager after enabling JWT auth:-503 Service Temporarily Unavailable

I followed the official doc of stream native (how-to-enable-authentication-and-authorization.md)

I am also facing the issue that how we can configure our pulsar-admin cli to do some operations.
Tried different method of auth with pulsar-admin cli but didn't work 

<img width="941" alt="Screenshot 2020-07-15 at 3 05 07 PM" src="https://user-images.githubusercontent.com/37150928/87529409-9550da80-c6ac-11ea-8fb4-d388cafbaf8a.png">
<img width="759" alt="Screenshot 2020-07-15 at 3 07 01 PM" src="https://user-images.githubusercontent.com/37150928/87529594-d943df80-c6ac-11ea-93d4-b84bc839ca78.png">
<img width="1278" alt="Screenshot 2020-07-15 at 3 22 42 PM" src="https://user-images.githubusercontent.com/37150928/87531223-08f3e700-c6af-11ea-97aa-5e35bc5c96da.png">

**Comment by kapilsingh421** [comment]
I found this is an issue of secret name that does not match as provided in stateful apps..
Even name is not fully mentioned in pods of broker and Pulsar manager.

Please look into this asap, this is a really bad issue if someone enables auth in charts
Helm chart version:-1.2.0,1.2.1
@sijie @yjshen @addisonj 


Thanks

**Comment by sijie** [comment]
@kapilsingh421 I see. The superUserRole for pulsar-manager was not added in the default value file. Will fix it today.
