### ISSUE TITLE
Helm charts are managing k8s namespace

### ISSUE THREAD

**Issue by Imunhatep** [streamnative/charts#140]
**Describe the bug**
Helm charts are managing namespace.  

helm does not position it self as a namespace manager, as namespaces in kubernetes are considered as a higher control structure that is not part of the application. 

**To Reproduce**
Use helm for installation without prior syncing namespaces in chart values and installation cmd:

```
kubectl create ns pulsartest
helm upgrade --install pulsar -n pulsartest streamnative/pulsar
Error: namespaces "pulsar" not found
```
even with `namespaceCreate: false`

**Expected behavior**
Do not manage kubernetes namespaces in helm charts.

* in case I failed to convince you, at least use consistent variables to refer to a proper namespace e.g. `{ .Release.Namespace }`

**Desktop (please complete the following information):**
 - Linux

**Comment by jiazhai** [comment]
@sijie Would you please help take a look at this issue?

**Comment by sijie** [comment]
@Imunhatep Agreed with you! You can set the `namespace` field in the values file to empty. Then the helm chart will use the namespace passed to helm command.  The `namespace` field was kept there for backward compatibility for old installations.
