### ISSUE TITLE
Support for rack aware scheduling

### ISSUE THREAD

**Issue by anvinjain** [streamnative/charts#153]
**Is your feature request related to a problem? Please describe.**
Charts like those of bookkeeper and zookeeper do not provide for a way to ensure that pod placement is rack aware

**Describe the solution you'd like**
Ability to configure appropriate label to use which can be used to get rack info and then ensuring that pods are not placed in the same rack. This should be optional.

**Describe alternatives you've considered**
No clear alternatives. 

**Additional context**
Discussed this with @addisonj in a different chat.

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
