### ISSUE TITLE
Add "Kubectl" alias param in config

### ISSUE THREAD

**Issue by f7753** [streamnative/charts#171]
In our environment, "kubectl" binary file name is not actually "kubectl",  but something else.
So, should we add a config for the "kubectl" alias?   While the default setting is "kubectl",  nothing different as what it is so far, then we can re-direct it to a certain filename from config.

**Comment by sijie** [comment]
@f7753 I am not sure if I understand your question. Can you clarify it?

**Comment by f7753** [comment]
Thank you for your reply.

In our environment, the binary file of kubectl's name  is "abc-kubectl-x" or some other literals like this.
So when I execute token gen scripts of this helm charts, it will find "kubectl" and execute, but it is not exactly the "abc-kubectl-x" that I really need to run with.

Hope this information could make the below comment a little clear:)

**Comment by sijie** [comment]
oh, I see. make sense. Are you interested in contributing a pull request?

**Comment by f7753** [comment]
Yes, I'll have a try.

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
