### ISSUE TITLE
Setting various metadataPrefix fails due to missing seperator

### ISSUE THREAD

**Issue by verbunk** [streamnative/charts#182]
In various parts of the chart templates there is a seperator '/' missing for Zook URIs.

e.g.
zookeeperServers: "{{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }}"

should be

zookeeperServers: "{{ template "pulsar.zookeeper.connect" . }}/{{ .Values.metadataPrefix }}"

so that the port doesn't combine with the metadata prefix.

With a custom template file with metadata prefix specified, the bad template snippet renders as,

```
#> helm template -f dev-values.yaml dev streamnative/pulsar | grep -n 2181pulsar-prd
831:  zookeeperServers: "dev-pulsar-zookeeper:2181pulsar-prd"
832:  configurationStoreServers: "dev-pulsar-zookeeper:2181pulsar-prd"
1717:  zookeeperServers: "dev-pulsar-zookeeper:2181pulsar-prd"
1718:  configurationStoreServers: "dev-pulsar-zookeeper:2181pulsar-prd"
5165:              --zookeeper dev-pulsar-zookeeper:2181pulsar-prd \
5166:              --configuration-store dev-pulsar-zookeeper:2181pulsar-prd \
```

Affected template files,

pulsar/templates/broker/broker-configmap.yaml
pulsar/templates/proxy/websocket-configmap.yaml
pulsar/templates/pulsar-cluster-initialize.yaml

**Comment by sijie** [comment]
@verbunk The `metadataPrefix` should start with "/". It is the full zookeeper path in zookeeper.

**Comment by verbunk** [comment]
Gotcha. Its expected to be written in the path. Thx!
