### ISSUE TITLE
[ENH] - Credentials (AWS/GCP/...) should be referenced as a secret name in values.yaml

### ISSUE THREAD

**Issue by verbunk** [streamnative/charts#184]
Hey Everyone, 

Small enhancement request for secret data (AWS/GCP credentials) be provided in the helm chart as a secret name which shoudl be expected to exist in the target namespace before deployment. It would keep the values a bit more protected and out of source code. :)

J

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
