### ISSUE TITLE
helm install pulsar-storage-provisioner streamnative/local-storage-provisioner  error

### ISSUE THREAD

**Issue by chenhuizi** [streamnative/charts#195]
[root@daspdev1 helm]# helm install local-storage-provisioner streamnative/local-storage-provisioner \
>     --set namespace=local-storage -n local-storage
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Comment by duktig-dev** [comment]
I think the "extensions/v1beta1" is deprecated in Kubernetes API. Assuming, this chart should be updated to accept new release.  (If I'm right ).

**Comment by javiramos1** [comment]
I'm also running into this issue

**Comment by bgrieder** [comment]
This worked for me:

1. Pull the charts:

```bash
helm pull streamnative/local-storage-provisioner --untar
```

2. In `local-storage-provisioner/templates/provisioner-gke.yaml`, change `extensions/v1beta1` to `apps/v1`.

3. install the updated charts
```bash
helm install local-storage-provisioner ./local-storage-provisioner --namespace pulsar
```
