### ISSUE TITLE
grafana overview cluster list is missing clusters

### ISSUE THREAD

**Issue by stevenarvar** [streamnative/charts#205]
We have three pulsar clusters in a simple helm release.  In the grafana overview page, the drop down menu only show two and one of the cluster name is wrong.  In the broker view however, the clusters show up correctly.  See attached screenshot.
<img width="1363" alt="Screen Shot 2021-04-15 at 9 28 40 AM" src="https://user-images.githubusercontent.com/36424528/114905015-541d6080-9dcd-11eb-851f-109cc80d63d9.png">

Broker view:
<img width="438" alt="Screen Shot 2021-04-15 at 9 32 45 AM" src="https://user-images.githubusercontent.com/36424528/114905237-95157500-9dcd-11eb-97ad-b5c16941fb82.png">

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
