### ISSUE TITLE
Pulsar Helm Chart  vs Pulsar-Operator Helm Chart

### ISSUE THREAD

**Issue by bradenwright** [streamnative/charts#242]
I found charts for:

* https://github.com/streamnative/charts/tree/master/charts/pulsar
* https://github.com/streamnative/charts/tree/master/charts/pulsar-operator

and I'm curious the differences, is there a good reason to use the operator?  Typically I think of using Operators to add some kind of business operations to the chart.  Things that don't fit eventual consistency.  Right now we've been evaluating the public chart https://pulsar.apache.org/docs/en/helm-overview/ but want to make sure I'm using the best helm chart for Pulsar.

Simplicity is a key factor since this will be deployed to lots of clients/k8s clusters

**Comment by sijie** [comment]
@bradenwright 

The [charts/pulsar](https://github.com/streamnative/charts/tree/master/charts/pulsar) is actually the same chart as the [open-source chart](https://github.com/apache/pulsar-helm-chart/). We actually contributed our chart to the Pulsar community. You can use either chart. They both work well.

The [charts/pulsar-operator](https://github.com/streamnative/charts/tree/master/charts/pulsar-operator) is the chart for installing Pulsar operators. Helm is great. But Helm templates are not the best tool to manage a stateful workload. Helm did not provide important features for running a stateful data service such as the ability to control deployment sequences and add additional operations between deployment steps. As a result, we developed the operators to provide Customer Resource Definitions and Controllers to manage and run Pulsar clusters in a more resilient way. You can read more from this [blog post](https://streamnative.io/en/blog/release/2021-06-16-streamnative-platform) and you can watch a presentation from one of our engineers (@fantapsody) in Pulsar Summit North America 2021 - "[Manage Pulsar Cluster Lifecycles with Kubernetes Operators](https://www.youtube.com/watch?v=363o60Lf4Ig&list=PLqRma1oIkcWjyezVodJHcp8GSypvGuc1C&index=9)".

Operators will definitely simplify a lot of managing and running Pulsar clusters on Kubernetes.

**Comment by Kiddinglife** [comment]
Hey @sijie, I did not see any configs related to k8s hpa configures in the operator example eg. minReplicas & maxRepilcas. Does that mean hap is Not supported by pulsar operator? Thank you.

**Comment by sijie** [comment]
@Kiddinglife - It is under development and coming in the next release.

**Comment by rayliu419** [comment]
Hi @sijie , 

"
Helm did not provide important features for running a stateful data service such as the ability to **control deployment sequences** and add additional operations between deployment steps.
"
There is a helm operator here : https://github.com/apache/pulsar-helm-chart 
Seems this operator implement control deployment sequences ? Based on my knowledge of pulsar, pulsar needs to setup zookeeper at first, if helm can't support deployment sequences, how does the above operator do ?

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
