### ISSUE TITLE
Service IP address

### ISSUE THREAD

**Issue by eaba** [streamnative/charts#30]
Hi @sijie 
I tried this out and it worked great!

Is there a way to pass the IP address of the Broker, Zookeeper and Bookkeeper services when installing?

I have tried out Helm's lookup function and encountered issues using it!
May be you can help in figuring it out!

I would not mind for a presto deployment example using charts!

**Comment by sijie** [comment]
> Is there a way to pass the IP address of the Broker, Zookeeper and Bookkeeper services when installing?

Do you mean advertising host IP address?

> I would not mind for a presto deployment example using charts!

Sure. We are adding that.

**Comment by eaba** [comment]
> Do you mean advertising host IP address?
````
 bin/pulsar initialize-cluster-metadata \
                --cluster eastus2 \
                --zookeeper 10.0.66.107:2181 \
                --configuration-store 10.0.66.107:2181 \
                --web-service-url http://10.0.237.95:8080/ \
                --broker-service-url pulsar://10.0.237.95:6650/ || true;
````
For me to achieve this I had to first create services and then copied the IP which helped in solving the issue I had using proxy.

I want this process automated and one of the things I tried was:
````
--zookeeper {{ (index (lookup "v1" "Service" "mynamespace" "myservice").status.loadBalancer.ingress 0).ip }}
````
And 
````
--zookeeper {{ (lookup "v1" "Service" "namespace" "service name").spec.clusterIP }}
````
In both cases I got nil exception

**Comment by eaba** [comment]
To deploy presto, I have this:
````
bin/apply-config-from-env.py conf/presto/config.properties
                    bin/apply-config-from-env.py conf/presto/catalog/pulsar.properties
                    bin/pulsar sql-worker run
````
I get this error:
````
File "bin/apply-config-from-env.py", line 50, in <module>
    k,v = line.split('=', 1)
ValueError: need more than 1 value to unpack
````

**Comment by sijie** [comment]
@eaba 

> For me to achieve this I had to first create services and then copied the IP which helped in solving the issue I had using the proxy.

I don't quite understand the motivation here. the initialize cluster metadata job just needs to run once and the options `--zookeeper <zk> --configuration-store <zk>` are used to point to the zookeeper cluster. The initialize task can run in the same k8s cluster along with zookeeper cluster,r so you can just the headless service of zookeeper cluster.

The web service URLs are only needed if you want to set up geo-replication. You can modify it by using `bin/pulsar-admin clusters update` to update those web service URLs. If you are installing a cluster using this helm, you can get the IP address of the proxy service and then using a separate task to update the cluster config. 

> bin/apply-config-from-env.py conf/presto/config.properties

For deploying presto, I don't think `apply-config-from-env.py` work for the presto config at this moment. Feel free to create an issue here. We can add one for you.

**Comment by eaba** [comment]
There isn't just enough detail in the documentation about this.

**Comment by eaba** [comment]
> The web service URLs are only needed if you want to set up geo-replication. You can modify it by using bin/pulsar-admin clusters update to update those web service URLs. If you are installing a cluster using this helm, you can get the IP address of the proxy service and then using a separate task to update the cluster config.

Can you show how this is done?

**Comment by sijie** [comment]
@eaba you can use this command to update cluster config : http://pulsar.apache.org/docs/en/admin-api-clusters/#pulsar-admin-2
