### ISSUE TITLE
Bookie pods won't start in SN Platform due to "Unrecognized VM option 'PrintGCTimeStamps'"

### ISSUE THREAD

**Issue by zbentley** [streamnative/charts#372]
Title says it all; if launched with the default settings for `PULSAR_GC`, bookies that come up fail their `init` pod due to the error `Unrecognized VM option 'PrintGCTimeStamps'`.

I'm not overriding `bookie` values at all, so as of the time of this writing the failure is occurring for the image `streamnative/sn-platform:2.8.1.4`.

**Comment by zbentley** [comment]
Additional incompatible options include:
- `PrintGCApplicationStoppedTime` 
- `AggressiveOpts` (Deprecated, slated for removal)
- `PrintHeapAtGC`
- `G1LogLevel=finest`
- `-Xloggc` (deprecated)

**Comment by fantapsody** [comment]
Fixed in https://github.com/streamnative/charts/pull/403
