### ISSUE TITLE
Deploy a Pulsar cluster with KoP occured KafkaListener error

### ISSUE THREAD

**Issue by forsake0120** [streamnative/charts#394]
We used helm3 to deploy pulsar cluster with Kop ( no istio and tls), our yaml set kop to true：
components:
  kop: true

but broker's pod occured KafkaListener by "“listeners or kafkaListeners is required”, it seems there is no place to input kafkaListeners in value.yaml

![图片](https://user-images.githubusercontent.com/24488347/143161628-676e4614-4868-42a4-89f7-f20ba763e750.png)

**Comment by ChenJhua** [comment]
@forsake0120 hello，I also encountered this problem. Trying to configure it still fails, can you tell me how to fix it? thanks
