### ISSUE TITLE
Cannot find version 0.6.0 of  pulsar_manager in dockerhub

### ISSUE THREAD

**Issue by forsake0120** [streamnative/charts#395]
pulsar_manager:
    repository: streamnative/pulsar-manager
    tag: 0.6.0
    pullPolicy: IfNotPresent
    hasCommand: false

but there is no such tag in dockerhub
![图片](https://user-images.githubusercontent.com/24488347/143169001-2994282e-b40c-47aa-bebf-b31fa62db52e.png)
![图片](https://user-images.githubusercontent.com/24488347/143169023-44d97f7f-1a88-40cb-acb3-c38ad0ca6b06.png)

**Comment by tuteng** [comment]
Fixed https://github.com/streamnative/charts/pull/388
