### ISSUE TITLE
stale repository tag gcr.io/google_containers/pause:0.3.0

### ISSUE THREAD

**Issue by ahothan** [streamnative/charts#444]
charts/sn-platform/values.yaml

has reference to gcr.io/google_containers/pause:0.3.0 which no longer exists.
there is a second reference to gcr.io/google_containers/pause:3.1 which is correct

both are related to imagePuller:
images.imagePuller
imagePuller

**Comment by ericsyh** [comment]
Duplicate with https://github.com/streamnative/charts/issues/698
