### ISSUE TITLE
Enable ability to supply external TLS certificates

### ISSUE THREAD

**Issue by romankuzmik** [streamnative/charts#480]
Currently if you want to enable TLS encryption on proxy-ingress, you also must enable cert-manager by setting both Values.tls.enabled and Values.tls.proxy.enabled to true. There are cases where the use of internal  cert-manager is not desired. In this cases external system will be responsible of generating certificates instead of cert-manager. We must accommodate this requirement.

It would be ok to leave proxy, broker and Co cert configuration intact, i.e. read certs from K8s Secrets. But at the same time we need to have an ability to disable cert-manager. External system will be generating certificates and uploading them as K8s Secrets in the places where proxy, broker and Co expects them to be.

**Comment by ericsyh** [comment]
@romankuzmik The proxy supports use a external TLS certificates, you can create a k8s secret with local tls cert and ca cert like the command as below: 

```
kubectl create secret generic <your proxy tls name> -n <your namespace> \
  --from-file=tls.crt=$(PWD)/cert/broker.cert.pem \
  --from-file=tls.key=$(PWD)/cert/broker.key-pk8.pem \
  --from-file=ca.crt=$(PWD)/cert/ca.cert.pem
```

Then apply this secret you created in the `proxy.tlsSecretName` https://github.com/streamnative/charts/blob/master/charts/sn-platform/values.yaml#L1487
