### ISSUE TITLE
[sn-platform] Install multiple separate clusters in the same Kubernetes cluster

### ISSUE THREAD

**Issue by sijie** [streamnative/charts#538]
*Motivation*

The user would like to install multiple separate clusters in one same Kubernetes cluster. But it doesn't appear possible to use the helm charts with defaults due to CRDs and ClusterRole being cluster scoped. Can you provide documentation for that?

**Comment by FushuWang** [comment]
@sijie 
I have tested the installation of multiple pulsar clusters, it will work when following below rules:
- Release name should be unique
- Only one release can install the component node-exporter of the monitoring stack

But I found some issues of grafana pannel:
- Pannel `Proxy Metrics`, `Overview` only has one cluster name as the selection option
- Pannel `Zookeeper` doesn't have metric data, and it doesn't have cluster names as selection options

![image1](https://streamnative.slack.com/files/U02JVRPH5FD/F038J34BHEY/image.png)
![image2](https://streamnative.slack.com/files/U02JVRPH5FD/F038J382GVA/image.png)
![image3](https://streamnative.slack.com/files/U02JVRPH5FD/F038UB8DCSD/image.png)

Should we fix these issues before providing the installation docs
