### ISSUE TITLE
Add Grafana Loki to the charts

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/charts#56]
There are two components in the Loki, Loki server and log agent named Promtail. All of these components support Helm installation. Here are tutorials for Loki and Promtail, https://github.com/grafana/loki/blob/v1.4.1/docs/installation/helm.md#installing-loki-with-helm. https://github.com/grafana/loki/blob/v1.4.1/docs/clients/promtail/installation.md#installing-promtail.

Loki also have a docker log driver. https://github.com/grafana/loki/tree/master/cmd/docker-driver#overview. This one is easier to use and looks don't need to install Promtail.

**Comment by jiazhai** [comment]
related to migration

**Comment by wolfstudy** [comment]
https://github.com/streamnative/charts/pull/57

**Comment by wolfstudy** [comment]
https://github.com/streamnative/apache-pulsar-grafana-dashboard/pull/29
