### ISSUE TITLE
Improve how GC parameters are configured for core pulsar components

### ISSUE THREAD

**Issue by fantapsody** [streamnative/charts#573]
Currently, it's a bit confusing and tedious to set GC parameters for pulsar core components, just like the one shown in the code snippet https://github.com/streamnative/charts/blob/master/charts/sn-platform/values.yaml#L874:
- when to use `BOOKIE_MEM` and `PULSAR_MEM`
- what are recommended parameters for GC and GC logs
- what are other recommended JVM options

A few possible improvements
- make GC/JVM configurations more structured, like `[broker/bookkeeper/zookeeper].jvm.[memoryOptions/gcOptions/gcLoggingOptions/extraOptions]`
- provide good defaults for each of these configurations

**Comment by Huanli-Meng** [comment]
The doc is updated.
