### ISSUE TITLE
[Node Dashboard] Only queries that return single series/table is supporteds

### ISSUE THREAD

**Issue by wolfstudy** [streamnative/charts#59]
When run different cluster in the same namespace, the several dashboards of node metrics show the following problems:

![image](https://user-images.githubusercontent.com/20965307/80080532-57985600-8584-11ea-9233-7c2cda3b50fd.png)

**Comment by ericsyh** [comment]
Close legacy issues in charts. Pls feel free to reopen the issue if this problem still exists in current version.
