### ISSUE TITLE
broker.extraEnv is used in Proxy instead of proxy.extraEnv

### ISSUE THREAD

**Issue by to-kr** [streamnative/charts#606]
I think that's a mistake, or am I wrong?

https://github.com/streamnative/charts/blob/e541207a37b642658980c84fe6efd2a4ed4e16ce/charts/pulsar/templates/proxy/proxy-statefulset.yaml#L244

**Comment by ericsyh** [comment]
@to-kr Yes, that's a mistake. Do you wanna take a PR to fix?
