### ISSUE TITLE
[Feature] Support specifying resource initContainers in sn-platform chart

### ISSUE THREAD

**Issue by MarvinCai** [streamnative/charts#611]
User might want fine grain control over resource used by initContainers, we should  support specifying resource for initContainer/initJob for sn-platform.

**Comment by yuweisung** [comment]
It will be better if we can expose the resource limit/request in init-container. Check the following link for the detail behavior.  In a large deployment, if we don't have initcontainer resource limit/request, the effective resource may be too big. 
Reference: 
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

**Comment by MarvinCai** [comment]
this is done, now pod resource request/limit will also apply to initContainer/initJob when deploying with operator version > 0.10.2.
