### ISSUE TITLE
helm install failed: No kind ingress in version extensions/v1beta1

### ISSUE THREAD

**Issue by yuweisung** [streamnative/charts#640]
Streamnative pulsar helm chart installation failed in kubernetes v1.22+. 

Symptom:
➜  pulsar-helm-chart git:(master) ✗ helm install sn -n pulsar streamnative/pulsar --set initialize=true 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"

Kubernetes version:
➜  pulsar-helm-chart git:(master) ✗ k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

Ingress API
➜  pulsar-helm-chart git:(master) ✗ k api-resources|grep ingress
ingressclasses                                      networking.k8s.io/v1                   false        IngressClass
ingresses                         ing               networking.k8s.io/v1                   true         Ingress

Reason: this api is deprecated and unavailable in 1.22+
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by ericsyh** [comment]
@yuweisung The new API for Ingress is `networking.k8s.io/v1` and it is only supported since k8s v1.19.  I worry about this migration will impact some users with previous k8s like v1.16 to v1.18.

**Comment by FushuWang** [comment]
We need to check the k8s version and set up the correct `apiVersion`, path format and ingress image. I have done this compatibility improvement in chart `sn-platform`. I will fix it
