### ISSUE TITLE
Support deploying operators with namespace-scoped permissions

### ISSUE THREAD

**Issue by fantapsody** [streamnative/charts#661]

**Comment by FushuWang** [comment]
There is a cluster role that seems like doesn't been used.  I didn't find a related role binding.  Should we consider removing it? @fantapsody 
https://github.com/streamnative/charts/blob/d5d0a72ba42e305e09636cda462b26307d1c08da/charts/pulsar-operator/templates/pulsar-operator/pulsar_broker_clusterrole.yaml#L24

**Comment by FushuWang** [comment]
> There is a cluster role that seems like doesn't been used. I didn't find a related role binding. Should we consider removing it? @fantapsody
> 
> https://github.com/streamnative/charts/blob/d5d0a72ba42e305e09636cda462b26307d1c08da/charts/pulsar-operator/templates/pulsar-operator/pulsar_broker_clusterrole.yaml#L24

I found the role binding. The operator will do the binding step. This cluster role is used to run functions.
https://github.com/streamnative/pulsar-operators/pull/242
