### ISSUE TITLE
Finish integrating builtin-connectors

### ISSUE THREAD

**Issue by sara-hannigan** [streamnative/charts#704]
This is related to https://github.com/streamnative/production/issues/64

**Comment by addisonj** [comment]
@nlu90 I believe this is complete? can you confirm

**Comment by nlu90** [comment]
Yes, this is finished in a flexible way.

1. Manually create the built-in connectors' ConfigMap inside a cluster and record the name.

2. Update the charts `values-pulsar.yaml` file's [field](https://github.com/streamnative/charts/blob/master/charts/pulsar/values.yaml#L1100) with the configMap name from step  one.
