### ISSUE TITLE
Cloudflare not supported as a DNS01 resolver in the public certificate issuing process

### ISSUE THREAD

**Issue by alesperme** [streamnative/charts#821]
Hi Guys!

I'm working with Pulsar in an environment in Google Kubernetes where we are using Cloudflare for security reasons and also for managing our DNS. Currently Cloudflare is not supported as a DNS resolver during public TLS certificate issuing process thus effectively preventing us to use Pulsar in production environment without patching helm templates. 

I've managed to locate and fix the issue in the in the TLS template section. If you would be so kind to give me the rights to push the changes to a branch and raise a merge request for your review, that would be great since then we won't need to patch helm chars for each version and others will be able to benefit from the change as well.

Thanks!

**Comment by sijie** [comment]
@alesperme We are happy to review and merge your changes. You can do this by forking the repo and submitting a pull request. see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by alesperme** [comment]
Done! Closing the issue.

Regards
