### ISSUE TITLE
can't log in to pulsar manager on streamnative platform

### ISSUE THREAD

**Issue by tomgreenwood1** [streamnative/charts#83]
I deployed the streamnative helm chart as per this guide https://github.com/streamnative/charts, however, when I go to log in to pulsar manager, neither (pulsar, pulsar) or (pulsarmanager, welovepulsar) works. I am missing something?

Thanks

**Comment by sijie** [comment]
@tomgreenwood1 

Are you using the chart from master or release 1.0.0?

If you are deploying the chart from the master, it uses the settings `pulsar_manager.superuser` to initialize the superuser for pulsar manager. The default credentials is (pulsarmanager, welovepulsar) if you haven't set the settings. You need to make sure the initialize job of pulsar manager is done. 

If you can show me the list of pods running after deploying the chart, I can help troubleshoot the problem.

**Comment by tomgreenwood1** [comment]
I was using the repo you get from running `helm repo add streamnative https://charts.streamnative.io/`,  so I guess that's the release? Weirdly, I was able to login as (pulsar, pulsar) once I set the chart to use the value images.pulsar_manager=apachepulsar/pulsar-manager. I'm afraid I'm moved back to using the official Apache chart now, so I can't check the pod init. Thanks for the help anyway.

**Comment by sijie** [comment]
@tomgreenwood1 understood. We are using the newer version of the pulsar manager. So the configuration of the superuser is a bit different from the current release. We are actively maintaining both the official Apache chart and our own chart. So either chart works. 

I am closing this issue for now. In case if you have any issues using SN chart in the future, feel free to open any issues.
