### ISSUE TITLE
Inconsistent APP VERSION on master and sn-platform-1.8.0

### ISSUE THREAD

**Issue by xiaogang-sn** [streamnative/charts#934]
https://github.com/streamnative/charts/blob/342a82585a9db8896d3db9681357fcdeefda4502/charts/sn-platform/Chart.yaml#L21 has `2.9` while https://github.com/streamnative/charts/blob/342a82585a9db8896d3db9681357fcdeefda4502/charts/sn-platform/values.yaml#L165 and other components all at `2.10.2.4`.

```
snp-k8s % helm search repo -l streamnative/sn-platform
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION
streamnative/sn-platform	1.8.0        	2.9        	StreamNative Platform Chart
streamnative/sn-platform	1.7.2        	2.10       	StreamNative Platform Chart
streamnative/sn-platform	1.7.1        	2.10       	StreamNative Platform Chart
streamnative/sn-platform	1.7.0        	2.10       	StreamNative Platform Chart
streamnative/sn-platform	1.6.4        	2.9        	StreamNative Platform Chart
[truncated]
```

/cc @ericsyh

**Comment by ericsyh** [comment]
Okay we will bump the `appVersion` on next patch release.

**Comment by xiaogang-sn** [comment]
Maybe we can add a trivial CI task to verify it in the future?

**Comment by ericsyh** [comment]
> Maybe we can add a trivial CI task to verify it in the future?

I think using CI to generate `appVersion` based on the image version of `sn-platform` will make more sense than add a verify CI job.
