### ISSUE TITLE
Chart and docker images license

### ISSUE THREAD

**Issue by mkozioro** [streamnative/charts#98]
Hi,

At https://pulsar.apache.org/docs/en/helm-overview/ I've found that official apache pulsar helm chart is based on this chart. I find streamnative chart superior to official one, as it contains required fixes. 
We've found that all or most of streamnative repositories are licensed under Apache2. But what about distributions published into https://charts.streamnative.io repository and docker images published on dockerhub (streamnative/platform, streamnative/apache-pulsar-grafana-dashboard-k8s, streamnative/pulsar-manager, streamnative/sn-pulsar).

**Comment by sijie** [comment]
@mkozioro sorry for the late response. Yes. currently, all the public available assets are under Apache License v2. I think we have included LICENSE files in those Github repos. You can check LICENSE file to reason about what license that repository and the related released assets are licensed under. Hope this clarifies your question.

**Comment by sijie** [comment]
@mkozioro Hope I answered your question. I am closing this issue now. If there are more questions, please open a new issue again.
